USE [master]
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'test_2021')
BEGIN
CREATE DATABASE [test_2021]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'test_2021', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\test_2021.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'test_2021_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\test_2021_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
END
GO

ALTER DATABASE [test_2021] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [test_2021].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [test_2021] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [test_2021] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [test_2021] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [test_2021] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [test_2021] SET ARITHABORT OFF 
GO

ALTER DATABASE [test_2021] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [test_2021] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [test_2021] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [test_2021] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [test_2021] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [test_2021] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [test_2021] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [test_2021] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [test_2021] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [test_2021] SET  DISABLE_BROKER 
GO

ALTER DATABASE [test_2021] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [test_2021] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [test_2021] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [test_2021] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [test_2021] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [test_2021] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [test_2021] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [test_2021] SET RECOVERY FULL 
GO

ALTER DATABASE [test_2021] SET  MULTI_USER 
GO

ALTER DATABASE [test_2021] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [test_2021] SET DB_CHAINING OFF 
GO

ALTER DATABASE [test_2021] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [test_2021] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [test_2021] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [test_2021] SET QUERY_STORE = OFF
GO

USE [test_2021]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [test_2021] SET  READ_WRITE 
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[t_Factor_Rating]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[t_Factor_Rating](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Rating] [varchar](100) NOT NULL,
	[Factor] [numeric](5, 2) NOT NULL,
 CONSTRAINT [PK_t_Factor_Rating] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[t_Rating_Occupation]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[t_Rating_Occupation](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Occupation] [varchar](100) NOT NULL,
	[Rating] [varchar](100) NOT NULL,
 CONSTRAINT [PK_t_Rating_Occupation] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO



